# Generated by Django 5.1.5 on 2025-02-06 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the goal.', max_length=200)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='The financial target amount to achieve.', max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text="The frequency of the goal: 'monthly' or 'yearly'.", max_length=10)),
                ('category', models.ForeignKey(blank=True, help_text='The category related to this goal (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='categories.category')),
                ('user', models.ForeignKey(help_text='The user who owns this financial goal.', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ['name'],
            },
        ),
    ]
