# Generated by Django 5.1.5 on 2025-02-06 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text="Type of transaction: 'income' for earnings, 'expense' for spending.", max_length=10)),
                ('date', models.DateField(help_text='The date when the transaction occurred.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of money involved in this transaction.', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Additional details or notes about the transaction.', null=True)),
                ('category', models.ForeignKey(help_text='The category associated with this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.category')),
                ('user', models.ForeignKey(help_text='The user who owns this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
